name: Run test cases
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Unit Tests
        run: go test -v ./...
