name: Publish Release build
on:
  release:
    types: [published]

jobs:
  tag:
    name: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: |
          git tag ${{ github.event.release.tag_name }}
          git push --tags
